apiVersion: v1
kind: Secret
metadata:
  name: euroscale-mollie
  namespace: euroscale
  labels:
    app: euroscale
    component: api
type: Opaque
stringData:
  api_key: test_Tfne9uUqrQf6TjgvKdSnHzFJjcxtuP
