// @generated by protoc-gen-connect-query v2.2.0 with parameter "target=ts"
// @generated from file euroscale/v1/database.proto (package euroscale.v1, syntax proto3)
/* eslint-disable */

import { DatabaseService } from "./database_pb";

/**
 * CreateDatabase provisions a new Vitess database with auto-generated credentials.
 * The credentials (username/password) are returned ONCE in this response and never again.
 *
 * @generated from rpc euroscale.v1.DatabaseService.CreateDatabase
 */
export const createDatabase = DatabaseService.method.createDatabase;

/**
 * DeleteDatabase drops a database and removes all associated credentials and secrets.
 *
 * @generated from rpc euroscale.v1.DatabaseService.DeleteDatabase
 */
export const deleteDatabase = DatabaseService.method.deleteDatabase;

/**
 * ListDatabases returns all databases owned by a given user.
 *
 * @generated from rpc euroscale.v1.DatabaseService.ListDatabases
 */
export const listDatabases = DatabaseService.method.listDatabases;

/**
 * GetDatabase returns metadata for a single database (no credentials).
 *
 * @generated from rpc euroscale.v1.DatabaseService.GetDatabase
 */
export const getDatabase = DatabaseService.method.getDatabase;

/**
 * RotateCredentials generates new credentials for an existing database,
 * invalidating the old ones. Returns the new credentials ONCE.
 *
 * @generated from rpc euroscale.v1.DatabaseService.RotateCredentials
 */
export const rotateCredentials = DatabaseService.method.rotateCredentials;

/**
 * GetIPWhitelist returns the IP whitelist for a database.
 *
 * @generated from rpc euroscale.v1.DatabaseService.GetIPWhitelist
 */
export const getIPWhitelist = DatabaseService.method.getIPWhitelist;

/**
 * AddIPWhitelistEntry adds a CIDR range to a database's IP whitelist.
 *
 * @generated from rpc euroscale.v1.DatabaseService.AddIPWhitelistEntry
 */
export const addIPWhitelistEntry = DatabaseService.method.addIPWhitelistEntry;

/**
 * RemoveIPWhitelistEntry removes a CIDR range from a database's IP whitelist.
 *
 * @generated from rpc euroscale.v1.DatabaseService.RemoveIPWhitelistEntry
 */
export const removeIPWhitelistEntry = DatabaseService.method.removeIPWhitelistEntry;

/**
 * GetUsage returns the current usage and tier limits for a user.
 *
 * @generated from rpc euroscale.v1.DatabaseService.GetUsage
 */
export const getUsage = DatabaseService.method.getUsage;

/**
 * SetUserTier updates the subscription tier for a user (admin only).
 *
 * @generated from rpc euroscale.v1.DatabaseService.SetUserTier
 */
export const setUserTier = DatabaseService.method.setUserTier;

/**
 * ResizeStorage expands a database's persistent volume by the specified GB.
 *
 * @generated from rpc euroscale.v1.DatabaseService.ResizeStorage
 */
export const resizeStorage = DatabaseService.method.resizeStorage;

/**
 * SetAutoscale enables/disables automatic storage scaling for a database.
 *
 * @generated from rpc euroscale.v1.DatabaseService.SetAutoscale
 */
export const setAutoscale = DatabaseService.method.setAutoscale;

/**
 * GetMetrics returns CPU and disk metrics for a database (last 24h).
 *
 * @generated from rpc euroscale.v1.DatabaseService.GetMetrics
 */
export const getMetrics = DatabaseService.method.getMetrics;

/**
 * GetSSLCertificates returns the SSL client certificates for a database.
 *
 * @generated from rpc euroscale.v1.DatabaseService.GetSSLCertificates
 */
export const getSSLCertificates = DatabaseService.method.getSSLCertificates;
