// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file euroscale/v1/database.proto (package euroscale.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AddIPWhitelistEntryRequest, AddIPWhitelistEntryResponse, CreateDatabaseRequest, CreateDatabaseResponse, DeleteDatabaseRequest, DeleteDatabaseResponse, GetDatabaseRequest, GetDatabaseResponse, GetIPWhitelistRequest, GetIPWhitelistResponse, GetMetricsRequest, GetMetricsResponse, GetSSLCertificatesRequest, GetSSLCertificatesResponse, GetUsageRequest, GetUsageResponse, ListDatabasesRequest, ListDatabasesResponse, RemoveIPWhitelistEntryRequest, RemoveIPWhitelistEntryResponse, ResizeComputeRequest, ResizeComputeResponse, ResizeStorageRequest, ResizeStorageResponse, RotateCredentialsRequest, RotateCredentialsResponse, SetAutoscaleRequest, SetAutoscaleResponse, SetUserTierRequest, SetUserTierResponse } from "./database_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * DatabaseService provisions and manages Vitess databases on demand.
 *
 * @generated from service euroscale.v1.DatabaseService
 */
export const DatabaseService = {
  typeName: "euroscale.v1.DatabaseService",
  methods: {
    /**
     * CreateDatabase provisions a new Vitess database with auto-generated credentials.
     * The credentials (username/password) are returned ONCE in this response and never again.
     *
     * @generated from rpc euroscale.v1.DatabaseService.CreateDatabase
     */
    createDatabase: {
      name: "CreateDatabase",
      I: CreateDatabaseRequest,
      O: CreateDatabaseResponse,
      kind: MethodKind.Unary,
    },
    /**
     * DeleteDatabase drops a database and removes all associated credentials and secrets.
     *
     * @generated from rpc euroscale.v1.DatabaseService.DeleteDatabase
     */
    deleteDatabase: {
      name: "DeleteDatabase",
      I: DeleteDatabaseRequest,
      O: DeleteDatabaseResponse,
      kind: MethodKind.Unary,
    },
    /**
     * ListDatabases returns all databases owned by a given user.
     *
     * @generated from rpc euroscale.v1.DatabaseService.ListDatabases
     */
    listDatabases: {
      name: "ListDatabases",
      I: ListDatabasesRequest,
      O: ListDatabasesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetDatabase returns metadata for a single database (no credentials).
     *
     * @generated from rpc euroscale.v1.DatabaseService.GetDatabase
     */
    getDatabase: {
      name: "GetDatabase",
      I: GetDatabaseRequest,
      O: GetDatabaseResponse,
      kind: MethodKind.Unary,
    },
    /**
     * RotateCredentials generates new credentials for an existing database,
     * invalidating the old ones. Returns the new credentials ONCE.
     *
     * @generated from rpc euroscale.v1.DatabaseService.RotateCredentials
     */
    rotateCredentials: {
      name: "RotateCredentials",
      I: RotateCredentialsRequest,
      O: RotateCredentialsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetIPWhitelist returns the IP whitelist for a database.
     *
     * @generated from rpc euroscale.v1.DatabaseService.GetIPWhitelist
     */
    getIPWhitelist: {
      name: "GetIPWhitelist",
      I: GetIPWhitelistRequest,
      O: GetIPWhitelistResponse,
      kind: MethodKind.Unary,
    },
    /**
     * AddIPWhitelistEntry adds a CIDR range to a database's IP whitelist.
     *
     * @generated from rpc euroscale.v1.DatabaseService.AddIPWhitelistEntry
     */
    addIPWhitelistEntry: {
      name: "AddIPWhitelistEntry",
      I: AddIPWhitelistEntryRequest,
      O: AddIPWhitelistEntryResponse,
      kind: MethodKind.Unary,
    },
    /**
     * RemoveIPWhitelistEntry removes a CIDR range from a database's IP whitelist.
     *
     * @generated from rpc euroscale.v1.DatabaseService.RemoveIPWhitelistEntry
     */
    removeIPWhitelistEntry: {
      name: "RemoveIPWhitelistEntry",
      I: RemoveIPWhitelistEntryRequest,
      O: RemoveIPWhitelistEntryResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetUsage returns the current usage and tier limits for a user.
     *
     * @generated from rpc euroscale.v1.DatabaseService.GetUsage
     */
    getUsage: {
      name: "GetUsage",
      I: GetUsageRequest,
      O: GetUsageResponse,
      kind: MethodKind.Unary,
    },
    /**
     * SetUserTier updates the subscription tier for a user (admin only).
     *
     * @generated from rpc euroscale.v1.DatabaseService.SetUserTier
     */
    setUserTier: {
      name: "SetUserTier",
      I: SetUserTierRequest,
      O: SetUserTierResponse,
      kind: MethodKind.Unary,
    },
    /**
     * ResizeStorage expands a database's persistent volume by the specified GB.
     *
     * @generated from rpc euroscale.v1.DatabaseService.ResizeStorage
     */
    resizeStorage: {
      name: "ResizeStorage",
      I: ResizeStorageRequest,
      O: ResizeStorageResponse,
      kind: MethodKind.Unary,
    },
    /**
     * SetAutoscale enables/disables automatic storage scaling for a database.
     *
     * @generated from rpc euroscale.v1.DatabaseService.SetAutoscale
     */
    setAutoscale: {
      name: "SetAutoscale",
      I: SetAutoscaleRequest,
      O: SetAutoscaleResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetMetrics returns CPU and disk metrics for a database (last 24h).
     *
     * @generated from rpc euroscale.v1.DatabaseService.GetMetrics
     */
    getMetrics: {
      name: "GetMetrics",
      I: GetMetricsRequest,
      O: GetMetricsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetSSLCertificates returns the SSL client certificates for a database.
     *
     * @generated from rpc euroscale.v1.DatabaseService.GetSSLCertificates
     */
    getSSLCertificates: {
      name: "GetSSLCertificates",
      I: GetSSLCertificatesRequest,
      O: GetSSLCertificatesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * ResizeCompute adjusts the compute units for a database instance.
     *
     * @generated from rpc euroscale.v1.DatabaseService.ResizeCompute
     */
    resizeCompute: {
      name: "ResizeCompute",
      I: ResizeComputeRequest,
      O: ResizeComputeResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

