// @generated by protoc-gen-connect-query v2.2.0 with parameter "target=ts"
// @generated from file euroscale/v1/metadata.proto (package euroscale.v1, syntax proto3)
/* eslint-disable */

import { MetadataService } from "./metadata_pb";

/**
 * ListSchemaDatabases returns all databases visible to the user through vtgate.
 *
 * @generated from rpc euroscale.v1.MetadataService.ListSchemaDatabases
 */
export const listSchemaDatabases = MetadataService.method.listSchemaDatabases;

/**
 * ListTables returns all tables in the given database visible to the user.
 *
 * @generated from rpc euroscale.v1.MetadataService.ListTables
 */
export const listTables = MetadataService.method.listTables;

/**
 * ListColumns returns column metadata for a table.
 *
 * @generated from rpc euroscale.v1.MetadataService.ListColumns
 */
export const listColumns = MetadataService.method.listColumns;

/**
 * PreviewTable returns the first N rows of a table for quick inspection.
 *
 * @generated from rpc euroscale.v1.MetadataService.PreviewTable
 */
export const previewTable = MetadataService.method.previewTable;
