// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file euroscale/v1/metadata.proto (package euroscale.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ListColumnsRequest, ListColumnsResponse, ListSchemaDatabasesRequest, ListSchemaDatabasesResponse, ListTablesRequest, ListTablesResponse, PreviewTableRequest, PreviewTableResponse } from "./metadata_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * MetadataService provides read-only introspection of the Vitess cluster
 * through INFORMATION_SCHEMA queries, scoped to what the authenticated user
 * can access.
 *
 * @generated from service euroscale.v1.MetadataService
 */
export const MetadataService = {
  typeName: "euroscale.v1.MetadataService",
  methods: {
    /**
     * ListSchemaDatabases returns all databases visible to the user through vtgate.
     *
     * @generated from rpc euroscale.v1.MetadataService.ListSchemaDatabases
     */
    listSchemaDatabases: {
      name: "ListSchemaDatabases",
      I: ListSchemaDatabasesRequest,
      O: ListSchemaDatabasesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * ListTables returns all tables in the given database visible to the user.
     *
     * @generated from rpc euroscale.v1.MetadataService.ListTables
     */
    listTables: {
      name: "ListTables",
      I: ListTablesRequest,
      O: ListTablesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * ListColumns returns column metadata for a table.
     *
     * @generated from rpc euroscale.v1.MetadataService.ListColumns
     */
    listColumns: {
      name: "ListColumns",
      I: ListColumnsRequest,
      O: ListColumnsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * PreviewTable returns the first N rows of a table for quick inspection.
     *
     * @generated from rpc euroscale.v1.MetadataService.PreviewTable
     */
    previewTable: {
      name: "PreviewTable",
      I: PreviewTableRequest,
      O: PreviewTableResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

