// @generated by protoc-gen-es v2.12.1 with parameter "target=ts"
// @generated from file euroscale/v1/metadata.proto (package euroscale.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file euroscale/v1/metadata.proto.
 */
export const file_euroscale_v1_metadata: GenFile = /*@__PURE__*/
  fileDesc("ChtldXJvc2NhbGUvdjEvbWV0YWRhdGEucHJvdG8SDGV1cm9zY2FsZS52MSJOChpMaXN0U2NoZW1hRGF0YWJhc2VzUmVxdWVzdBIPCgd1c2VyX2lkGAEgASgJEhEKCXBhZ2Vfc2l6ZRgCIAEoBRIMCgRwYWdlGAMgASgFImAKG0xpc3RTY2hlbWFEYXRhYmFzZXNSZXNwb25zZRIRCglkYXRhYmFzZXMYASADKAkSDQoFdG90YWwYAiABKAUSDAoEcGFnZRgDIAEoBRIRCglwYWdlX3NpemUYBCABKAUiVwoRTGlzdFRhYmxlc1JlcXVlc3QSDwoHdXNlcl9pZBgBIAEoCRIQCghkYXRhYmFzZRgCIAEoCRIRCglwYWdlX3NpemUYAyABKAUSDAoEcGFnZRgEIAEoBSJUChJMaXN0VGFibGVzUmVzcG9uc2USDgoGdGFibGVzGAEgAygJEg0KBXRvdGFsGAIgASgFEgwKBHBhZ2UYAyABKAUSEQoJcGFnZV9zaXplGAQgASgFImcKEkxpc3RDb2x1bW5zUmVxdWVzdBIPCgd1c2VyX2lkGAEgASgJEhAKCGRhdGFiYXNlGAIgASgJEg0KBXRhYmxlGAMgASgJEhEKCXBhZ2Vfc2l6ZRgEIAEoBRIMCgRwYWdlGAUgASgFIpcBCgpDb2x1bW5JbmZvEgwKBG5hbWUYASABKAkSEQoJZGF0YV90eXBlGAIgASgJEhMKC2lzX251bGxhYmxlGAMgASgJEhYKDmNvbHVtbl9kZWZhdWx0GAQgASgJEhIKCmNvbHVtbl9rZXkYBSABKAkSDQoFZXh0cmEYBiABKAkSGAoQb3JkaW5hbF9wb3NpdGlvbhgHIAEoBSJwChNMaXN0Q29sdW1uc1Jlc3BvbnNlEikKB2NvbHVtbnMYASADKAsyGC5ldXJvc2NhbGUudjEuQ29sdW1uSW5mbxINCgV0b3RhbBgCIAEoBRIMCgRwYWdlGAMgASgFEhEKCXBhZ2Vfc2l6ZRgEIAEoBSJWChNQcmV2aWV3VGFibGVSZXF1ZXN0Eg8KB3VzZXJfaWQYASABKAkSEAoIZGF0YWJhc2UYAiABKAkSDQoFdGFibGUYAyABKAkSDQoFbGltaXQYBCABKAUiYwoUUHJldmlld1RhYmxlUmVzcG9uc2USDwoHY29sdW1ucxgBIAMoCRIfCgRyb3dzGAIgAygLMhEuZXVyb3NjYWxlLnYxLlJvdxIZChFhcHByb3hpbWF0ZV90b3RhbBgDIAEoAyIVCgNSb3cSDgoGdmFsdWVzGAEgAygJMvkCCg9NZXRhZGF0YVNlcnZpY2USagoTTGlzdFNjaGVtYURhdGFiYXNlcxIoLmV1cm9zY2FsZS52MS5MaXN0U2NoZW1hRGF0YWJhc2VzUmVxdWVzdBopLmV1cm9zY2FsZS52MS5MaXN0U2NoZW1hRGF0YWJhc2VzUmVzcG9uc2USTwoKTGlzdFRhYmxlcxIfLmV1cm9zY2FsZS52MS5MaXN0VGFibGVzUmVxdWVzdBogLmV1cm9zY2FsZS52MS5MaXN0VGFibGVzUmVzcG9uc2USUgoLTGlzdENvbHVtbnMSIC5ldXJvc2NhbGUudjEuTGlzdENvbHVtbnNSZXF1ZXN0GiEuZXVyb3NjYWxlLnYxLkxpc3RDb2x1bW5zUmVzcG9uc2USVQoMUHJldmlld1RhYmxlEiEuZXVyb3NjYWxlLnYxLlByZXZpZXdUYWJsZVJlcXVlc3QaIi5ldXJvc2NhbGUudjEuUHJldmlld1RhYmxlUmVzcG9uc2VCUFpOZ2l0aHViLmNvbS9zcHNjcmVhdGlvbnMvZXVyb3NjYWxlLXN0YXJ0dXAta2l0L2FwaS9nZW4vZXVyb3NjYWxlL3YxO2V1cm9zY2FsZXYxYgZwcm90bzM");

/**
 * @generated from message euroscale.v1.ListSchemaDatabasesRequest
 */
export type ListSchemaDatabasesRequest = Message<"euroscale.v1.ListSchemaDatabasesRequest"> & {
  /**
   * Required. User ID to look up credentials for.
   *
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * Optional. Maximum databases per page (default 25, max 100).
   *
   * @generated from field: int32 page_size = 2;
   */
  pageSize: number;

  /**
   * Optional. Offset for offset-based pagination.
   *
   * @generated from field: int32 page = 3;
   */
  page: number;
};

/**
 * Describes the message euroscale.v1.ListSchemaDatabasesRequest.
 * Use `create(ListSchemaDatabasesRequestSchema)` to create a new message.
 */
export const ListSchemaDatabasesRequestSchema: GenMessage<ListSchemaDatabasesRequest> = /*@__PURE__*/
  messageDesc(file_euroscale_v1_metadata, 0);

/**
 * @generated from message euroscale.v1.ListSchemaDatabasesResponse
 */
export type ListSchemaDatabasesResponse = Message<"euroscale.v1.ListSchemaDatabasesResponse"> & {
  /**
   * List of database names the user can access.
   *
   * @generated from field: repeated string databases = 1;
   */
  databases: string[];

  /**
   * Total number of accessible databases.
   *
   * @generated from field: int32 total = 2;
   */
  total: number;

  /**
   * Current page (0-indexed).
   *
   * @generated from field: int32 page = 3;
   */
  page: number;

  /**
   * Page size used.
   *
   * @generated from field: int32 page_size = 4;
   */
  pageSize: number;
};

/**
 * Describes the message euroscale.v1.ListSchemaDatabasesResponse.
 * Use `create(ListSchemaDatabasesResponseSchema)` to create a new message.
 */
export const ListSchemaDatabasesResponseSchema: GenMessage<ListSchemaDatabasesResponse> = /*@__PURE__*/
  messageDesc(file_euroscale_v1_metadata, 1);

/**
 * @generated from message euroscale.v1.ListTablesRequest
 */
export type ListTablesRequest = Message<"euroscale.v1.ListTablesRequest"> & {
  /**
   * Required. User ID to look up credentials for.
   *
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * Required. Database/keyspace name to list tables from.
   *
   * @generated from field: string database = 2;
   */
  database: string;

  /**
   * Optional. Maximum tables per page (default 50, max 100).
   *
   * @generated from field: int32 page_size = 3;
   */
  pageSize: number;

  /**
   * Optional. Offset for offset-based pagination.
   *
   * @generated from field: int32 page = 4;
   */
  page: number;
};

/**
 * Describes the message euroscale.v1.ListTablesRequest.
 * Use `create(ListTablesRequestSchema)` to create a new message.
 */
export const ListTablesRequestSchema: GenMessage<ListTablesRequest> = /*@__PURE__*/
  messageDesc(file_euroscale_v1_metadata, 2);

/**
 * @generated from message euroscale.v1.ListTablesResponse
 */
export type ListTablesResponse = Message<"euroscale.v1.ListTablesResponse"> & {
  /**
   * List of table names.
   *
   * @generated from field: repeated string tables = 1;
   */
  tables: string[];

  /**
   * Total number of tables.
   *
   * @generated from field: int32 total = 2;
   */
  total: number;

  /**
   * Current page (0-indexed).
   *
   * @generated from field: int32 page = 3;
   */
  page: number;

  /**
   * Page size used.
   *
   * @generated from field: int32 page_size = 4;
   */
  pageSize: number;
};

/**
 * Describes the message euroscale.v1.ListTablesResponse.
 * Use `create(ListTablesResponseSchema)` to create a new message.
 */
export const ListTablesResponseSchema: GenMessage<ListTablesResponse> = /*@__PURE__*/
  messageDesc(file_euroscale_v1_metadata, 3);

/**
 * @generated from message euroscale.v1.ListColumnsRequest
 */
export type ListColumnsRequest = Message<"euroscale.v1.ListColumnsRequest"> & {
  /**
   * Required. User ID to look up credentials for.
   *
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * Required. Database/keyspace name.
   *
   * @generated from field: string database = 2;
   */
  database: string;

  /**
   * Required. Table name.
   *
   * @generated from field: string table = 3;
   */
  table: string;

  /**
   * Optional. Maximum columns per page (default 50, max 100).
   *
   * @generated from field: int32 page_size = 4;
   */
  pageSize: number;

  /**
   * Optional. Offset for offset-based pagination.
   *
   * @generated from field: int32 page = 5;
   */
  page: number;
};

/**
 * Describes the message euroscale.v1.ListColumnsRequest.
 * Use `create(ListColumnsRequestSchema)` to create a new message.
 */
export const ListColumnsRequestSchema: GenMessage<ListColumnsRequest> = /*@__PURE__*/
  messageDesc(file_euroscale_v1_metadata, 4);

/**
 * ColumnInfo describes a single column.
 *
 * @generated from message euroscale.v1.ColumnInfo
 */
export type ColumnInfo = Message<"euroscale.v1.ColumnInfo"> & {
  /**
   * Column name.
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * SQL data type (e.g. "varchar(255)", "int", "text").
   *
   * @generated from field: string data_type = 2;
   */
  dataType: string;

  /**
   * Whether the column is nullable ("YES"/"NO").
   *
   * @generated from field: string is_nullable = 3;
   */
  isNullable: string;

  /**
   * Column default value, if any.
   *
   * @generated from field: string column_default = 4;
   */
  columnDefault: string;

  /**
   * Column key ("PRI", "UNI", "MUL", or empty).
   *
   * @generated from field: string column_key = 5;
   */
  columnKey: string;

  /**
   * Extra info (e.g. "auto_increment").
   *
   * @generated from field: string extra = 6;
   */
  extra: string;

  /**
   * Ordinal position (1-indexed).
   *
   * @generated from field: int32 ordinal_position = 7;
   */
  ordinalPosition: number;
};

/**
 * Describes the message euroscale.v1.ColumnInfo.
 * Use `create(ColumnInfoSchema)` to create a new message.
 */
export const ColumnInfoSchema: GenMessage<ColumnInfo> = /*@__PURE__*/
  messageDesc(file_euroscale_v1_metadata, 5);

/**
 * @generated from message euroscale.v1.ListColumnsResponse
 */
export type ListColumnsResponse = Message<"euroscale.v1.ListColumnsResponse"> & {
  /**
   * List of column metadata.
   *
   * @generated from field: repeated euroscale.v1.ColumnInfo columns = 1;
   */
  columns: ColumnInfo[];

  /**
   * Total number of columns.
   *
   * @generated from field: int32 total = 2;
   */
  total: number;

  /**
   * Current page (0-indexed).
   *
   * @generated from field: int32 page = 3;
   */
  page: number;

  /**
   * Page size used.
   *
   * @generated from field: int32 page_size = 4;
   */
  pageSize: number;
};

/**
 * Describes the message euroscale.v1.ListColumnsResponse.
 * Use `create(ListColumnsResponseSchema)` to create a new message.
 */
export const ListColumnsResponseSchema: GenMessage<ListColumnsResponse> = /*@__PURE__*/
  messageDesc(file_euroscale_v1_metadata, 6);

/**
 * @generated from message euroscale.v1.PreviewTableRequest
 */
export type PreviewTableRequest = Message<"euroscale.v1.PreviewTableRequest"> & {
  /**
   * Required. User ID to look up credentials for.
   *
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * Required. Database/keyspace name.
   *
   * @generated from field: string database = 2;
   */
  database: string;

  /**
   * Required. Table name.
   *
   * @generated from field: string table = 3;
   */
  table: string;

  /**
   * Optional. Max rows to return (default 10, max 100).
   *
   * @generated from field: int32 limit = 4;
   */
  limit: number;
};

/**
 * Describes the message euroscale.v1.PreviewTableRequest.
 * Use `create(PreviewTableRequestSchema)` to create a new message.
 */
export const PreviewTableRequestSchema: GenMessage<PreviewTableRequest> = /*@__PURE__*/
  messageDesc(file_euroscale_v1_metadata, 7);

/**
 * @generated from message euroscale.v1.PreviewTableResponse
 */
export type PreviewTableResponse = Message<"euroscale.v1.PreviewTableResponse"> & {
  /**
   * Column names in order.
   *
   * @generated from field: repeated string columns = 1;
   */
  columns: string[];

  /**
   * Row data — each row is a list of string values matching column order.
   *
   * @generated from field: repeated euroscale.v1.Row rows = 2;
   */
  rows: Row[];

  /**
   * Total rows in the table (approximate, from INFORMATION_SCHEMA).
   *
   * @generated from field: int64 approximate_total = 3;
   */
  approximateTotal: bigint;
};

/**
 * Describes the message euroscale.v1.PreviewTableResponse.
 * Use `create(PreviewTableResponseSchema)` to create a new message.
 */
export const PreviewTableResponseSchema: GenMessage<PreviewTableResponse> = /*@__PURE__*/
  messageDesc(file_euroscale_v1_metadata, 8);

/**
 * Row is a single row of data, with each value as a string.
 *
 * @generated from message euroscale.v1.Row
 */
export type Row = Message<"euroscale.v1.Row"> & {
  /**
   * @generated from field: repeated string values = 1;
   */
  values: string[];
};

/**
 * Describes the message euroscale.v1.Row.
 * Use `create(RowSchema)` to create a new message.
 */
export const RowSchema: GenMessage<Row> = /*@__PURE__*/
  messageDesc(file_euroscale_v1_metadata, 9);

/**
 * MetadataService provides read-only introspection of the Vitess cluster
 * through INFORMATION_SCHEMA queries, scoped to what the authenticated user
 * can access.
 *
 * @generated from service euroscale.v1.MetadataService
 */
export const MetadataService: GenService<{
  /**
   * ListSchemaDatabases returns all databases visible to the user through vtgate.
   *
   * @generated from rpc euroscale.v1.MetadataService.ListSchemaDatabases
   */
  listSchemaDatabases: {
    methodKind: "unary";
    input: typeof ListSchemaDatabasesRequestSchema;
    output: typeof ListSchemaDatabasesResponseSchema;
  },
  /**
   * ListTables returns all tables in the given database visible to the user.
   *
   * @generated from rpc euroscale.v1.MetadataService.ListTables
   */
  listTables: {
    methodKind: "unary";
    input: typeof ListTablesRequestSchema;
    output: typeof ListTablesResponseSchema;
  },
  /**
   * ListColumns returns column metadata for a table.
   *
   * @generated from rpc euroscale.v1.MetadataService.ListColumns
   */
  listColumns: {
    methodKind: "unary";
    input: typeof ListColumnsRequestSchema;
    output: typeof ListColumnsResponseSchema;
  },
  /**
   * PreviewTable returns the first N rows of a table for quick inspection.
   *
   * @generated from rpc euroscale.v1.MetadataService.PreviewTable
   */
  previewTable: {
    methodKind: "unary";
    input: typeof PreviewTableRequestSchema;
    output: typeof PreviewTableResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_euroscale_v1_metadata, 0);

