// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: euroscale/v1/database.proto

package euroscalev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DatabaseService_CreateDatabase_FullMethodName         = "/euroscale.v1.DatabaseService/CreateDatabase"
	DatabaseService_DeleteDatabase_FullMethodName         = "/euroscale.v1.DatabaseService/DeleteDatabase"
	DatabaseService_ListDatabases_FullMethodName          = "/euroscale.v1.DatabaseService/ListDatabases"
	DatabaseService_GetDatabase_FullMethodName            = "/euroscale.v1.DatabaseService/GetDatabase"
	DatabaseService_RotateCredentials_FullMethodName      = "/euroscale.v1.DatabaseService/RotateCredentials"
	DatabaseService_GetIPWhitelist_FullMethodName         = "/euroscale.v1.DatabaseService/GetIPWhitelist"
	DatabaseService_AddIPWhitelistEntry_FullMethodName    = "/euroscale.v1.DatabaseService/AddIPWhitelistEntry"
	DatabaseService_RemoveIPWhitelistEntry_FullMethodName = "/euroscale.v1.DatabaseService/RemoveIPWhitelistEntry"
	DatabaseService_GetUsage_FullMethodName               = "/euroscale.v1.DatabaseService/GetUsage"
	DatabaseService_SetUserTier_FullMethodName            = "/euroscale.v1.DatabaseService/SetUserTier"
	DatabaseService_ResizeStorage_FullMethodName          = "/euroscale.v1.DatabaseService/ResizeStorage"
)

// DatabaseServiceClient is the client API for DatabaseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DatabaseService provisions and manages Vitess databases on demand.
type DatabaseServiceClient interface {
	// CreateDatabase provisions a new Vitess database with auto-generated credentials.
	// The credentials (username/password) are returned ONCE in this response and never again.
	CreateDatabase(ctx context.Context, in *CreateDatabaseRequest, opts ...grpc.CallOption) (*CreateDatabaseResponse, error)
	// DeleteDatabase drops a database and removes all associated credentials and secrets.
	DeleteDatabase(ctx context.Context, in *DeleteDatabaseRequest, opts ...grpc.CallOption) (*DeleteDatabaseResponse, error)
	// ListDatabases returns all databases owned by a given user.
	ListDatabases(ctx context.Context, in *ListDatabasesRequest, opts ...grpc.CallOption) (*ListDatabasesResponse, error)
	// GetDatabase returns metadata for a single database (no credentials).
	GetDatabase(ctx context.Context, in *GetDatabaseRequest, opts ...grpc.CallOption) (*GetDatabaseResponse, error)
	// RotateCredentials generates new credentials for an existing database,
	// invalidating the old ones. Returns the new credentials ONCE.
	RotateCredentials(ctx context.Context, in *RotateCredentialsRequest, opts ...grpc.CallOption) (*RotateCredentialsResponse, error)
	// GetIPWhitelist returns the IP whitelist for a database.
	GetIPWhitelist(ctx context.Context, in *GetIPWhitelistRequest, opts ...grpc.CallOption) (*GetIPWhitelistResponse, error)
	// AddIPWhitelistEntry adds a CIDR range to a database's IP whitelist.
	AddIPWhitelistEntry(ctx context.Context, in *AddIPWhitelistEntryRequest, opts ...grpc.CallOption) (*AddIPWhitelistEntryResponse, error)
	// RemoveIPWhitelistEntry removes a CIDR range from a database's IP whitelist.
	RemoveIPWhitelistEntry(ctx context.Context, in *RemoveIPWhitelistEntryRequest, opts ...grpc.CallOption) (*RemoveIPWhitelistEntryResponse, error)
	// GetUsage returns the current usage and tier limits for a user.
	GetUsage(ctx context.Context, in *GetUsageRequest, opts ...grpc.CallOption) (*GetUsageResponse, error)
	// SetUserTier updates the subscription tier for a user (admin only).
	SetUserTier(ctx context.Context, in *SetUserTierRequest, opts ...grpc.CallOption) (*SetUserTierResponse, error)
	// ResizeStorage expands a database's persistent volume by the specified GB.
	ResizeStorage(ctx context.Context, in *ResizeStorageRequest, opts ...grpc.CallOption) (*ResizeStorageResponse, error)
}

type databaseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDatabaseServiceClient(cc grpc.ClientConnInterface) DatabaseServiceClient {
	return &databaseServiceClient{cc}
}

func (c *databaseServiceClient) CreateDatabase(ctx context.Context, in *CreateDatabaseRequest, opts ...grpc.CallOption) (*CreateDatabaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDatabaseResponse)
	err := c.cc.Invoke(ctx, DatabaseService_CreateDatabase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseServiceClient) DeleteDatabase(ctx context.Context, in *DeleteDatabaseRequest, opts ...grpc.CallOption) (*DeleteDatabaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDatabaseResponse)
	err := c.cc.Invoke(ctx, DatabaseService_DeleteDatabase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseServiceClient) ListDatabases(ctx context.Context, in *ListDatabasesRequest, opts ...grpc.CallOption) (*ListDatabasesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDatabasesResponse)
	err := c.cc.Invoke(ctx, DatabaseService_ListDatabases_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseServiceClient) GetDatabase(ctx context.Context, in *GetDatabaseRequest, opts ...grpc.CallOption) (*GetDatabaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDatabaseResponse)
	err := c.cc.Invoke(ctx, DatabaseService_GetDatabase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseServiceClient) RotateCredentials(ctx context.Context, in *RotateCredentialsRequest, opts ...grpc.CallOption) (*RotateCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RotateCredentialsResponse)
	err := c.cc.Invoke(ctx, DatabaseService_RotateCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseServiceClient) GetIPWhitelist(ctx context.Context, in *GetIPWhitelistRequest, opts ...grpc.CallOption) (*GetIPWhitelistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIPWhitelistResponse)
	err := c.cc.Invoke(ctx, DatabaseService_GetIPWhitelist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseServiceClient) AddIPWhitelistEntry(ctx context.Context, in *AddIPWhitelistEntryRequest, opts ...grpc.CallOption) (*AddIPWhitelistEntryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddIPWhitelistEntryResponse)
	err := c.cc.Invoke(ctx, DatabaseService_AddIPWhitelistEntry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseServiceClient) RemoveIPWhitelistEntry(ctx context.Context, in *RemoveIPWhitelistEntryRequest, opts ...grpc.CallOption) (*RemoveIPWhitelistEntryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveIPWhitelistEntryResponse)
	err := c.cc.Invoke(ctx, DatabaseService_RemoveIPWhitelistEntry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseServiceClient) GetUsage(ctx context.Context, in *GetUsageRequest, opts ...grpc.CallOption) (*GetUsageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUsageResponse)
	err := c.cc.Invoke(ctx, DatabaseService_GetUsage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseServiceClient) SetUserTier(ctx context.Context, in *SetUserTierRequest, opts ...grpc.CallOption) (*SetUserTierResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetUserTierResponse)
	err := c.cc.Invoke(ctx, DatabaseService_SetUserTier_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseServiceClient) ResizeStorage(ctx context.Context, in *ResizeStorageRequest, opts ...grpc.CallOption) (*ResizeStorageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResizeStorageResponse)
	err := c.cc.Invoke(ctx, DatabaseService_ResizeStorage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DatabaseServiceServer is the server API for DatabaseService service.
// All implementations must embed UnimplementedDatabaseServiceServer
// for forward compatibility.
//
// DatabaseService provisions and manages Vitess databases on demand.
type DatabaseServiceServer interface {
	// CreateDatabase provisions a new Vitess database with auto-generated credentials.
	// The credentials (username/password) are returned ONCE in this response and never again.
	CreateDatabase(context.Context, *CreateDatabaseRequest) (*CreateDatabaseResponse, error)
	// DeleteDatabase drops a database and removes all associated credentials and secrets.
	DeleteDatabase(context.Context, *DeleteDatabaseRequest) (*DeleteDatabaseResponse, error)
	// ListDatabases returns all databases owned by a given user.
	ListDatabases(context.Context, *ListDatabasesRequest) (*ListDatabasesResponse, error)
	// GetDatabase returns metadata for a single database (no credentials).
	GetDatabase(context.Context, *GetDatabaseRequest) (*GetDatabaseResponse, error)
	// RotateCredentials generates new credentials for an existing database,
	// invalidating the old ones. Returns the new credentials ONCE.
	RotateCredentials(context.Context, *RotateCredentialsRequest) (*RotateCredentialsResponse, error)
	// GetIPWhitelist returns the IP whitelist for a database.
	GetIPWhitelist(context.Context, *GetIPWhitelistRequest) (*GetIPWhitelistResponse, error)
	// AddIPWhitelistEntry adds a CIDR range to a database's IP whitelist.
	AddIPWhitelistEntry(context.Context, *AddIPWhitelistEntryRequest) (*AddIPWhitelistEntryResponse, error)
	// RemoveIPWhitelistEntry removes a CIDR range from a database's IP whitelist.
	RemoveIPWhitelistEntry(context.Context, *RemoveIPWhitelistEntryRequest) (*RemoveIPWhitelistEntryResponse, error)
	// GetUsage returns the current usage and tier limits for a user.
	GetUsage(context.Context, *GetUsageRequest) (*GetUsageResponse, error)
	// SetUserTier updates the subscription tier for a user (admin only).
	SetUserTier(context.Context, *SetUserTierRequest) (*SetUserTierResponse, error)
	// ResizeStorage expands a database's persistent volume by the specified GB.
	ResizeStorage(context.Context, *ResizeStorageRequest) (*ResizeStorageResponse, error)
	mustEmbedUnimplementedDatabaseServiceServer()
}

// UnimplementedDatabaseServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDatabaseServiceServer struct{}

func (UnimplementedDatabaseServiceServer) CreateDatabase(context.Context, *CreateDatabaseRequest) (*CreateDatabaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDatabase not implemented")
}
func (UnimplementedDatabaseServiceServer) DeleteDatabase(context.Context, *DeleteDatabaseRequest) (*DeleteDatabaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDatabase not implemented")
}
func (UnimplementedDatabaseServiceServer) ListDatabases(context.Context, *ListDatabasesRequest) (*ListDatabasesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDatabases not implemented")
}
func (UnimplementedDatabaseServiceServer) GetDatabase(context.Context, *GetDatabaseRequest) (*GetDatabaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDatabase not implemented")
}
func (UnimplementedDatabaseServiceServer) RotateCredentials(context.Context, *RotateCredentialsRequest) (*RotateCredentialsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RotateCredentials not implemented")
}
func (UnimplementedDatabaseServiceServer) GetIPWhitelist(context.Context, *GetIPWhitelistRequest) (*GetIPWhitelistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIPWhitelist not implemented")
}
func (UnimplementedDatabaseServiceServer) AddIPWhitelistEntry(context.Context, *AddIPWhitelistEntryRequest) (*AddIPWhitelistEntryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddIPWhitelistEntry not implemented")
}
func (UnimplementedDatabaseServiceServer) RemoveIPWhitelistEntry(context.Context, *RemoveIPWhitelistEntryRequest) (*RemoveIPWhitelistEntryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveIPWhitelistEntry not implemented")
}
func (UnimplementedDatabaseServiceServer) GetUsage(context.Context, *GetUsageRequest) (*GetUsageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUsage not implemented")
}
func (UnimplementedDatabaseServiceServer) SetUserTier(context.Context, *SetUserTierRequest) (*SetUserTierResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetUserTier not implemented")
}
func (UnimplementedDatabaseServiceServer) ResizeStorage(context.Context, *ResizeStorageRequest) (*ResizeStorageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResizeStorage not implemented")
}
func (UnimplementedDatabaseServiceServer) mustEmbedUnimplementedDatabaseServiceServer() {}
func (UnimplementedDatabaseServiceServer) testEmbeddedByValue()                         {}

// UnsafeDatabaseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DatabaseServiceServer will
// result in compilation errors.
type UnsafeDatabaseServiceServer interface {
	mustEmbedUnimplementedDatabaseServiceServer()
}

func RegisterDatabaseServiceServer(s grpc.ServiceRegistrar, srv DatabaseServiceServer) {
	// If the following call panics, it indicates UnimplementedDatabaseServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DatabaseService_ServiceDesc, srv)
}

func _DatabaseService_CreateDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServiceServer).CreateDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatabaseService_CreateDatabase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServiceServer).CreateDatabase(ctx, req.(*CreateDatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseService_DeleteDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServiceServer).DeleteDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatabaseService_DeleteDatabase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServiceServer).DeleteDatabase(ctx, req.(*DeleteDatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseService_ListDatabases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDatabasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServiceServer).ListDatabases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatabaseService_ListDatabases_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServiceServer).ListDatabases(ctx, req.(*ListDatabasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseService_GetDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServiceServer).GetDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatabaseService_GetDatabase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServiceServer).GetDatabase(ctx, req.(*GetDatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseService_RotateCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServiceServer).RotateCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatabaseService_RotateCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServiceServer).RotateCredentials(ctx, req.(*RotateCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseService_GetIPWhitelist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIPWhitelistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServiceServer).GetIPWhitelist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatabaseService_GetIPWhitelist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServiceServer).GetIPWhitelist(ctx, req.(*GetIPWhitelistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseService_AddIPWhitelistEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddIPWhitelistEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServiceServer).AddIPWhitelistEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatabaseService_AddIPWhitelistEntry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServiceServer).AddIPWhitelistEntry(ctx, req.(*AddIPWhitelistEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseService_RemoveIPWhitelistEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveIPWhitelistEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServiceServer).RemoveIPWhitelistEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatabaseService_RemoveIPWhitelistEntry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServiceServer).RemoveIPWhitelistEntry(ctx, req.(*RemoveIPWhitelistEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseService_GetUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServiceServer).GetUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatabaseService_GetUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServiceServer).GetUsage(ctx, req.(*GetUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseService_SetUserTier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUserTierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServiceServer).SetUserTier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatabaseService_SetUserTier_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServiceServer).SetUserTier(ctx, req.(*SetUserTierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseService_ResizeStorage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResizeStorageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServiceServer).ResizeStorage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatabaseService_ResizeStorage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServiceServer).ResizeStorage(ctx, req.(*ResizeStorageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DatabaseService_ServiceDesc is the grpc.ServiceDesc for DatabaseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DatabaseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "euroscale.v1.DatabaseService",
	HandlerType: (*DatabaseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDatabase",
			Handler:    _DatabaseService_CreateDatabase_Handler,
		},
		{
			MethodName: "DeleteDatabase",
			Handler:    _DatabaseService_DeleteDatabase_Handler,
		},
		{
			MethodName: "ListDatabases",
			Handler:    _DatabaseService_ListDatabases_Handler,
		},
		{
			MethodName: "GetDatabase",
			Handler:    _DatabaseService_GetDatabase_Handler,
		},
		{
			MethodName: "RotateCredentials",
			Handler:    _DatabaseService_RotateCredentials_Handler,
		},
		{
			MethodName: "GetIPWhitelist",
			Handler:    _DatabaseService_GetIPWhitelist_Handler,
		},
		{
			MethodName: "AddIPWhitelistEntry",
			Handler:    _DatabaseService_AddIPWhitelistEntry_Handler,
		},
		{
			MethodName: "RemoveIPWhitelistEntry",
			Handler:    _DatabaseService_RemoveIPWhitelistEntry_Handler,
		},
		{
			MethodName: "GetUsage",
			Handler:    _DatabaseService_GetUsage_Handler,
		},
		{
			MethodName: "SetUserTier",
			Handler:    _DatabaseService_SetUserTier_Handler,
		},
		{
			MethodName: "ResizeStorage",
			Handler:    _DatabaseService_ResizeStorage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "euroscale/v1/database.proto",
}
